version: '3.9'

services:
  coderr_web:
    build: .
    image: coderr:latest
    container_name: coderr_web
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - webnet
    expose:
      - "8000"
