# Generated by Django 5.2.5 on 2025-09-08 10:14

import app_auth.models
import app_auth.storages
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('business', 'Business'), ('customer', 'Customer')], max_length=8)),
                ('file', models.FileField(blank=True, storage=app_auth.storages.OverwriteStorage(), upload_to=app_auth.models.profile_picture_path)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('tel', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('working_hours', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
