# Generated by Django 5.2.5 on 2025-09-02 11:39

import app_auth.models
import app_auth.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file',
            field=models.FileField(blank=True, storage=app_auth.storages.OverwriteStorage(), upload_to=app_auth.models.profile_picture_path),
        ),
    ]
